/**
 * Application error codes shared by the API and the frontend (PRD §86).
 * The frontend maps codes to customer-facing copy; it never renders raw error messages.
 */
export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',
  DUPLICATE_REQUEST: 'DUPLICATE_REQUEST',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_UNAVAILABLE: 'ACCOUNT_UNAVAILABLE',
  TWO_FACTOR_REQUIRED: 'TWO_FACTOR_REQUIRED',
  INVALID_TWO_FACTOR_CODE: 'INVALID_TWO_FACTOR_CODE',
  CSRF_REJECTED: 'CSRF_REJECTED',
  PRODUCT_INACTIVE: 'PRODUCT_INACTIVE',
  QUANTITY_OUT_OF_RANGE: 'QUANTITY_OUT_OF_RANGE',
  PRICE_VERSION_CONFLICT: 'PRICE_VERSION_CONFLICT',
  PRICING_RULE_VIOLATION: 'PRICING_RULE_VIOLATION',
  INVALID_PRODUCT_STATE: 'INVALID_PRODUCT_STATE',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_UNAVAILABLE: 'PRODUCT_UNAVAILABLE',
  /** Source name taken, or a balance change that would make inventory negative. */
  INVALID_SOURCE_STATE: 'INVALID_SOURCE_STATE',
  PRICE_CHANGED: 'PRICE_CHANGED',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  DUPLICATE_IDEMPOTENCY_KEY: 'DUPLICATE_IDEMPOTENCY_KEY',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_NOT_CANCELLABLE: 'ORDER_NOT_CANCELLABLE',
  ORDER_CREATION_FAILED: 'ORDER_CREATION_FAILED',
  STAFF_CANNOT_ORDER: 'STAFF_CANNOT_ORDER',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  INVALID_ORDER_TRANSITION: 'INVALID_ORDER_TRANSITION',
  ORDER_NOT_PAYABLE: 'ORDER_NOT_PAYABLE',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_METHOD_UNAVAILABLE: 'PAYMENT_METHOD_UNAVAILABLE',
  PAYMENT_ALREADY_PENDING: 'PAYMENT_ALREADY_PENDING',
  PAYMENT_IN_PROGRESS: 'PAYMENT_IN_PROGRESS',
  PAYMENT_GATEWAY_UNAVAILABLE: 'PAYMENT_GATEWAY_UNAVAILABLE',
  PAYMENT_GATEWAY_REJECTED: 'PAYMENT_GATEWAY_REJECTED',
  PAYMENT_AMOUNT_MISMATCH: 'PAYMENT_AMOUNT_MISMATCH',
  WEBHOOK_PAYLOAD_INVALID: 'WEBHOOK_PAYLOAD_INVALID',
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

/** Shape of every error response body returned by the API. */
export interface ApiErrorBody {
  code: ErrorCode;
  message: string;
  requestId: string;
}
